# Generated by Django 6.0 on 2025-12-13 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('manage_service_division', 'Can manage service division'), ('view_own_service_division', 'Can view own service division'), ('manage_own_service_division', 'Can manage own service division')],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('location_hint', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('manage_zone', 'Can manage zone'), ('view_own_zone', 'Can view own zone'), ('manage_own_zone', 'Can manage own zone')],
            },
        ),
        migrations.CreateModel(
            name='ServiceLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_leaderships', to='members.member')),
                ('service_division', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_leader', to='structure.servicedivision')),
            ],
            options={
                'ordering': ['service_division', 'member'],
                'permissions': [('manage_service_leader', 'Can manage service leader')],
            },
        ),
        migrations.CreateModel(
            name='ZoneLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_leaderships', to='members.member')),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zone_leader', to='structure.zone')),
            ],
            options={
                'ordering': ['zone', 'member'],
                'permissions': [('manage_zone_leader', 'Can manage zone leader')],
            },
        ),
        migrations.CreateModel(
            name='ZoneGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('children', 'Children Sunday School'), ('teenagers', 'Teenagers Bible Study'), ('parents', 'Parents Bible Study')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_groups', to='structure.zone')),
            ],
            options={
                'ordering': ['zone', 'group_type', 'name'],
                'permissions': [('manage_zone_group', 'Can manage zone group')],
                'unique_together': {('zone', 'group_type', 'name')},
            },
        ),
    ]
