# Generated by Django 6.0 on 2025-12-13 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_gender'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleStudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Bible Study Group', max_length=150)),
                ('place_of_study', models.CharField(blank=True, help_text='Location or place where the study takes place', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leaders', models.ManyToManyField(blank=True, help_text='Leaders of this Bible Study Group', related_name='led_bible_study_groups', to='members.member')),
                ('members', models.ManyToManyField(blank=True, help_text='Members participating in this Bible Study Group', related_name='bible_study_groups', to='members.member')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_study_groups', to='structure.zone')),
            ],
            options={
                'verbose_name': 'Bible Study Group',
                'verbose_name_plural': 'Bible Study Groups',
                'ordering': ['zone', 'name'],
                'permissions': [('manage_bible_study_group', 'Can manage bible study group')],
            },
        ),
    ]
