# Generated by Django 6.0 on 2025-12-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_biblestudygroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedivision',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='is_active',
        ),
    ]
