# Generated by Django 6.0 on 2025-12-13 05:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='blog/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'permissions': [('manage_blog_post', 'Can manage blog post')],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/backgrounds/')),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_link', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('layout', models.CharField(choices=[('classic', 'Classic'), ('left_image', 'Image Left'), ('right_image', 'Image Right'), ('overlay_dark', 'Dark Overlay'), ('overlay_light', 'Light Overlay')], default='classic', max_length=20)),
                ('text_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10)),
                ('button_variant', models.CharField(choices=[('primary', 'Primary'), ('outline', 'Outline'), ('ghost', 'Ghost')], default='primary', max_length=20)),
                ('title_color', models.CharField(default='#000000', max_length=20)),
                ('subtitle_color', models.CharField(default='#666666', max_length=20)),
                ('overlay_opacity', models.DecimalField(decimal_places=2, default=0.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('extra_classes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('manage_hero_section', 'Can manage hero section')],
            },
        ),
        migrations.CreateModel(
            name='SocialFeedConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube')], max_length=20)),
                ('handle_or_page_id', models.CharField(max_length=255)),
                ('api_key_or_token', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['platform', 'handle_or_page_id'],
                'permissions': [('manage_social_feed_config', 'Can manage social feed config')],
            },
        ),
    ]
