# Generated by Django 6.0 on 2025-12-13 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='members.member'),
        ),
        migrations.AlterUniqueTogether(
            name='socialfeedconfig',
            unique_together={('platform', 'handle_or_page_id')},
        ),
    ]
