# Generated by Django 6.0 on 2025-12-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
