# Generated by Django 6.0 on 2025-12-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_herosection_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Photo image', upload_to='photos/')),
                ('date', models.DateField(help_text='Date when the photo was taken')),
                ('year', models.IntegerField(help_text='Year for grouping photos')),
                ('title', models.CharField(blank=True, help_text='Optional title for the photo', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the photo')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this photo should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'permissions': [('manage_photo', 'Can manage photo')],
            },
        ),
    ]
