# Generated by Django 6.0 on 2025-12-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='socialfeedconfig',
            name='is_active',
        ),
    ]
