# Generated by Django 6.0 on 2025-12-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username'], 'permissions': [('view_dashboard', 'Can view dashboard')], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
