# Generated by Django 6.0 on 2025-12-13 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Families',
                'ordering': ['created_at'],
                'permissions': [('manage_family', 'Can manage family')],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff_member', models.BooleanField(default=False)),
                ('staff_title', models.CharField(blank=True, max_length=150)),
                ('staff_bio', models.TextField(blank=True)),
                ('show_in_staff_page', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'permissions': [('manage_member', 'Can manage member'), ('view_zone_members', 'Can view zone members'), ('manage_zone_members', 'Can manage zone members'), ('view_service_members', 'Can view service division members'), ('manage_service_members', 'Can manage service division members')],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('son', 'Son'), ('daughter', 'Daughter'), ('guardian', 'Guardian'), ('other', 'Other')], max_length=20)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='members.family')),
            ],
            options={
                'ordering': ['relationship', 'member__first_name'],
                'permissions': [('manage_family_member', 'Can manage family member')],
            },
        ),
    ]
