# Generated by Django 6.0 on 2025-12-13 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='service_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='structure.servicedivision'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link to User for staff members', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='structure.zone'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_relationships', to='members.member'),
        ),
        migrations.AddField(
            model_name='family',
            name='head_member',
            field=models.ForeignKey(blank=True, help_text='Head of family (father or mother)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_families', to='members.member'),
        ),
        migrations.AlterUniqueTogether(
            name='familymember',
            unique_together={('family', 'member')},
        ),
    ]
