# Generated by Django 6.0 on 2025-12-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(blank=True, help_text='Age in years (if date of birth is unknown)', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='use_age_instead_of_birthdate',
            field=models.BooleanField(default=False, help_text='Use age instead of date of birth'),
        ),
    ]
