# Generated by Django 6.0 on 2025-12-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_age_member_use_age_instead_of_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='father_name',
            field=models.CharField(blank=True, help_text="Father's name", max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(help_text="Grandfather's name", max_length=100),
        ),
    ]
